version: '3.7'
services:
  ollama:
    container_name: ollama
    image: ollama/ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    environment:
      - OPENBLAS_NUM_THREADS=8

volumes:
  ollama:
